### ISSUE TITLE
Radio button

### ISSUE THREAD

**Issue by gearspoint** [nicoaudy/laravelmanthra#16]
Sir, Please tell me the command for the radio button. Thanks in advance.

**Comment by nicoaudy** [comment]
Hi @gearspoint 👋,
You can use boolean type to generate radio button.

```bash
php artisan manthra:web Cat --fields="name#string; age#integer; is_male#boolean" --model-namespace=Models
```

Thanks

**Comment by gearspoint** [comment]
Thank You very much sir,
